name: AstroDistri CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  # --- 1: BACKEND (Django REST) ---
  backend-ci:
    runs-on: ubuntu-24.04  
    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Configurar Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Instalar Dependencias
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel 
          pip install -r requirements.txt

      - name: Validar Estructura y Tests
        run: |
          python manage.py check
          # python manage.py test

  # --- 2: FRONTEND (React) ---
  frontend-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar y Construir
        working-directory: ./client 
        run: |
          npm install
          npm run build